#!/bin/sh

rm *.aux
rm *.bbl
rm *.blg
rm *.log
rm *~
rm *.dvi

latex genebot.tex && latex genebot.tex &&  latex genebot.tex && bibtex genebot && latex genebot.tex && latex genebot.tex && latex genebot.tex && echo "-----------------------------" && dvips genebot.dvi -o && ps2pdf genebot.ps && echo " "
